name: Build and Publish Docker Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  #schedule:
  #  - cron: '35 4 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  #pull_request:
  #  branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  DOCKER_REGISTRY_URL: docker.io
  #DOCKER_REGISTRY_OWNER: ${{ env.CI_REPOSITORY_OWNER }}
  DOCKER_REGISTRY_OWNER: tatyano
  #DOCKER_REGISTRY_IMAGE: ${{ env.CI_REPOSITORY }}
  DOCKER_REGISTRY_IMAGE: k8s-athenz-sia
  DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      discussions: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    steps:
      # A GitHub Action to expose useful environment variables.
      # https://github.com/FranzDiebold/github-env-vars-action
      -
        name: GitHub Environment Variables Action
        id: env
        # uses: https://github.com/FranzDiebold/github-env-vars-action/tags
        uses: FranzDiebold/github-env-vars-action@v2

      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      # https://github.com/actions/checkout
      -
        name: Checkout repository
        id: checkout
        # You may pin to the exact commit or the version.
        # uses: https://github.com/actions/checkout/tags
        uses: actions/checkout@v2

      # The Github action runs CIS Dockerfile benchmark against dockerfiles in repository (CIS 4.1, 4.2, 4.3, 4.6, 4.7, 4.9, 4.10)
      # https://github.com/sysdiglabs/benchmark-dockerfile
      -
        name: Sysdig Benchmark Dockerfile
        id: sysdig
        # You may pin to the exact commit or the version.
        # uses: https://github.com/sysdiglabs/benchmark-dockerfile/tags
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        with:
          # Directory of dockerfiles (default "./")
          directory: "./"
          # list of disallowed packages separated by comma (default ")
          #disallowedPackages: ''
          # list of trusted base images separated by comma (default "", meaning trust any base image)
          trustedBaseImages: ""

      # The Github action runs CIS Dockerfile benchmark against dockerfiles in repository (CIS 4.1, 4.2, 4.3, 4.6, 4.7, 4.9, 4.10)
      # https://github.com/sysdiglabs/benchmark-dockerfile
      -
        name: Post Sysdig Benchmark Dockerfile
        id: postsysdig
        run: |
          echo ${{ toJSON(steps.sysdig.outputs.violation_report) }} | \
            jq -r .
          echo ${{ toJSON(steps.sysdig.outputs.violation_report) }} | \
            jq -r .cis_docker_benchmark_violation_report[].violations[] | \
            wc -l | \
            xargs -I% test 0 -eq %

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      -
        name: Extract Docker metadata
        id: meta
        if: github.event_name != 'pull_request'
        # You may pin to the exact commit or the version.
        # uses: https://github.com/docker/metadata-action/tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REGISTRY_OWNER }}/${{ env.DOCKER_REGISTRY_IMAGE }}
          # for latest tag
          # latest=auto for tagging latest only for "master" branch
          flavor: |
            latest=true
          # eg. refs/heads/master
          # eg. refs/pull/318/merge
          # shorthand for {{major}}.{{minor}}.{{patch}} (can include pre-release)
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=pr
            type=semver,pattern={{version}}

      # GitHub Action to login against a Docker registry.
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      -
        name: Docker Login to registry ${{ env.DOCKER_REGISTRY_URL }}
        id: login
        if: github.event_name != 'pull_request'
        # You may pin to the exact commit or the version.
        # uses: https://github.com/docker/login-action/tags
        uses: docker/login-action@v1
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.DOCKER_REGISTRY_URL }} # optional
          # Username used to log against the Docker registry
          username: ${{ env.DOCKER_REGISTRY_OWNER }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ env.DOCKER_REGISTRY_TOKEN }} # optional
          # Log out from the Docker registry at the end of a job
          logout: true # optional, default is true

      # GitHub Action to install QEMU static binaries.
      # https://github.com/docker/setup-qemu-action
      -
        name: Set up QEMU
        id: qemu
        # You may pin to the exact commit or the version.
        # uses: https://github.com/docker/setup-qemu-action/tags
        uses: docker/setup-qemu-action@v1

      # GitHub Action to set up Docker Buildx.
      # https://github.com/docker/setup-buildx-action
      -
        name: Set up Docker Buildx
        id: buildx
        if: github.event_name != 'pull_request'
        # You may pin to the exact commit or the version.
        # uses: https://github.com/docker/setup-buildx-action/tags
        uses: docker/setup-buildx-action@v1

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      -
        name: Build and push Docker image for linux/amd64 and linux/arm64 
        id: build_and_push
        # You may pin to the exact commit or the version.
        # uses: https://github.com/docker/build-push-action/tags
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

