name: lint

on:
  # If any commit message in your push or the HEAD commit of your PR contains the strings
  # [skip ci], [ci skip], [no ci], [skip actions], or [actions skip]
  # workflows triggered on the push or pull_request events will be skipped.
  # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:

  # This job runs markdownlint and reports issues from linters.
  # https://github.com/DavidAnson/markdownlint-cli2-action
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        continue-on-error: true
        with:
          globs: |
            README.md
            CHANGELOG.md
            docs/*.md
